=== VovanSuper/VEGALearn/metadata-SAMPLE_11.dtd
<!ELEMENT SYSTEM (MODULES,GROUPS_MENU,ATTRIBUTES,GROUPS_ATTRIBUTES,TABLES,ACTIONS,REPORTS,FORMS)>
<!ATTLIST SYSTEM id NMTOKEN #REQUIRED>
<!ATTLIST SYSTEM name CDATA #REQUIRED>
<!ELEMENT MODULES (MODULE)>
<!ATTLIST MODULES id NMTOKEN #REQUIRED>
<!ATTLIST MODULES name NMTOKEN #REQUIRED>
<!ELEMENT MODULE EMPTY>
<!ATTLIST MODULE id NMTOKEN #REQUIRED>
<!ATTLIST MODULE name CDATA #REQUIRED>
<!ATTLIST MODULE menu NMTOKEN #REQUIRED>
<!ELEMENT GROUPS_MENU (MENU)>
<!ATTLIST GROUPS_MENU name CDATA #REQUIRED>
<!ELEMENT MENU (MENU*,MI*,COMMENT*)>
<!ATTLIST MENU id NMTOKEN #IMPLIED>
<!ATTLIST MENU name CDATA #IMPLIED>
<!ELEMENT MI EMPTY>
<!ATTLIST MI name CDATA #IMPLIED>
<!ATTLIST MI type CDATA #IMPLIED>
<!ATTLIST MI formlist NMTOKEN #IMPLIED>
<!ATTLIST MI actionlist CDATA #IMPLIED>
<!ELEMENT COMMENT EMPTY>
<!ATTLIST COMMENT name CDATA #REQUIRED>
<!ELEMENT ATTRIBUTES (A+,COMMENT+)?>
<!ATTLIST ATTRIBUTES name NMTOKEN #REQUIRED>
<!ELEMENT A (AI*)>
<!ATTLIST A id NMTOKEN #REQUIRED>
<!ATTLIST A name CDATA #IMPLIED>
<!ATTLIST A caption CDATA #IMPLIED>
<!ATTLIST A type (boolean|date|int|list|number|ref|string|text) #IMPLIED>
<!ATTLIST A table NMTOKEN #IMPLIED><!ATTLIST A ret (AGENT2_ID_ret|CODE|GEO_TERR_ID_ret|ID|NAME|YEAR) #IMPLIED>
<!ATTLIST A form NMTOKEN #IMPLIED>
<!ATTLIST A nulls CDATA #IMPLIED>
<!ATTLIST A labelwidth NMTOKEN #IMPLIED>
<!ATTLIST A where CDATA #IMPLIED>
<!ATTLIST A len (10|11|12|13|14|18.4|18.2|2|20|3|3.1|34|4|8|80|9) #IMPLIED>
<!ATTLIST A formula CDATA #IMPLIED><!ATTLIST A local (true) #IMPLIED>
<!ATTLIST A readonly (false|true) #IMPLIED>
<!ATTLIST A array (false|true) #IMPLIED>
<!ATTLIST A virtual (true) #IMPLIED>
<!ATTLIST A visible (false|form|grid|true) #IMPLIED><!ATTLIST A width (100|20|25|30|33|34|35|40|50|60|65|70) #IMPLIED><!ATTLIST A pid NMTOKEN #IMPLIED><!ATTLIST A parentkey (cascade|nocascade) #IMPLIED><!ATTLIST A query CDATA #IMPLIED><!ATTLIST A value CDATA #IMPLIED><!ATTLIST A button (email|true|web) #IMPLIED><!ATTLIST A format CDATA #IMPLIED><!ELEMENT AI EMPTY><!ATTLIST AI id CDATA #REQUIRED><!ATTLIST AI name CDATA #IMPLIED><!ATTLIST AI readonly NMTOKEN #IMPLIED><!ELEMENT GROUPS_ATTRIBUTES (COMMENT+,GA+)?><!ATTLIST GROUPS_ATTRIBUTES name CDATA #REQUIRED><!ELEMENT GA (A*,GA*)><!ATTLIST GA id (AgentAddr|BKD_CODE_GR|BKD_VID_KDB|CONTROL_ORG|DEBIT|DEBITOR|DictionaryBC|DictionaryNote|DictionaryParam|Document|DocumentAutoNumb|DocumentAutoNumbP|DocumentP|ENF_DOC|ENF_PROC|GeoParam|INCOM_SUB_VID_KDB|ParamAddr|SubjectRF|YEAR_BUDGET) #IMPLIED><!ATTLIST GA name CDATA #IMPLIED><!ATTLIST GA caption CDATA #IMPLIED><!ATTLIST GA width NMTOKEN #IMPLIED><!ELEMENT TABLES (TABLE*,COMMENT*)><!ATTLIST TABLES name NMTOKEN #REQUIRED><!ELEMENT TABLE (A*,TI*,GA*,TABS?,COMMENT?)><!ATTLIST TABLE id ID #REQUIRED><!ATTLIST TABLE name CDATA #REQUIRED><!ATTLIST TABLE order CDATA #IMPLIED><!ATTLIST TABLE hid (CODE|IDX|NAME) #IMPLIED><!ATTLIST TABLE tablename (AGENT|AGENT_ACC|AGENT_ADDR|AGENT_PERSONS|DICNOMNS) #IMPLIED><!ATTLIST TABLE virtual NMTOKEN #IMPLIED><!ATTLIST TABLE where CDATA #IMPLIED><!ATTLIST TABLE caption CDATA #IMPLIED><!ELEMENT TI EMPTY><!ATTLIST TI unique CDATA #REQUIRED><!ATTLIST TI id ID #IMPLIED><!ATTLIST TI name CDATA #IMPLIED><!ELEMENT TABS (TAB+)><!ATTLIST TABS name CDATA #IMPLIED> <!ELEMENT TAB (A*,GA*,COMMENT?,GRID*,TABS?)><!ATTLIST TAB name CDATA #REQUIRED><!ATTLIST TAB id NMTOKEN #IMPLIED><!ELEMENT ACTIONS (ACTION*,COMMENT*,MI*)><!ATTLIST ACTIONS name NMTOKEN #REQUIRED><!ELEMENT ACTION (P*,FORM?)><!ATTLIST ACTION id ID #REQUIRED><!ATTLIST ACTION name CDATA #REQUIRED><!ATTLIST ACTION type (link|procedure|script) #REQUIRED><!ATTLIST ACTION href CDATA #IMPLIED><!ATTLIST ACTION visible NMTOKEN #IMPLIED><!ATTLIST ACTION actionlist CDATA #IMPLIED><!ATTLIST ACTION refresh (all) #IMPLIED><!ATTLIST ACTION procedure NMTOKEN #IMPLIED><!ELEMENT P EMPTY><!ATTLIST P id (convname|errorone|handbookname|val) #REQUIRED><!ATTLIST P value CDATA #REQUIRED><!ELEMENT FORM (A*,GA*,GRID*,TABS?)><!ATTLIST FORM name CDATA #IMPLIED><!ATTLIST FORM id ID #IMPLIED><!ELEMENT REPORTS EMPTY><!ATTLIST REPORTS name NMTOKEN #REQUIRED><!ELEMENT FORMS (COMMENT*,FORM*)><!ATTLIST FORMS id NMTOKEN #REQUIRED><!ATTLIST FORMS name NMTOKEN #REQUIRED><!ELEMENT GRID (MENU?)><!ATTLIST GRID id NMTOKEN #IMPLIED><!ATTLIST GRID name CDATA #REQUIRED><!ATTLIST GRID table NMTOKEN #REQUIRED><!ATTLIST GRID readonly (false|true) #IMPLIED>
<!ATTLIST AI actionlist NMTOKEN #IMPLIED>
<!ATTLIST GRID actionlist CDATA #IMPLIED>

=== VovanSuper/VEGALearn/metadata_1983.xml
<!DOCTYPE SYSTEM SYSTEM "metadata-SAMPLE_11.dtd">
<SYSTEM id="1983" name="Тестовая конфигурация Овсюков В.А">
	<MODULES id="Modules" name="Модули">
		<MODULE id="ModuleVovan1983" name="Vovan Ovsyukov Test Module" menu="ModuleVovan1983" />
	</MODULES>
	<GROUPS_MENU name="Группы меню Vovan">
		<MENU id="ModuleVovan1983" name="Меню модуля Vovan Module">
			<MENU name="Файл">
				<MI name="Параметры системы" formlist="Options"/>
				<MI name="Загруженные файлы" formlist="Filelinks"/>
				<MI type="line" />
				<MI name="Выйти" actionlist="Exit"/>
			</MENU>
			<MENU name="Справочники">
				<MI name="Users" formlist="Person" />
			</MENU>
			<MENU name="Sites">
				<MI name="Сайт Menfin" actionlist="MenfinSiteRef" />
			</MENU>
			<MENU name="Forms">
				<MI name="Направления работ" formlist="JobsDirections1983" />
				<MI name="Files" formlist="Docs1983" />
			</MENU>
			<MENU name="Documents">
				<MI name="Документы" formlist="Docs1983" />
				<MI name="Документы (спецификации справа)" formlist="Doc_1983" />
			</MENU>
			<MENU name="Help">
				<MI name="Руководство пользователя" actionlist="HelpNciUser"/>
			</MENU>
		</MENU>
	</GROUPS_MENU>
	<ATTRIBUTES name="Атрибуты"/>
	<GROUPS_ATTRIBUTES name="Группы атрибутов"/>
	<TABLES name="Таблицы">
		<TABLE id="JOBSDIRECTIONS1983" name="Jobs Directions (направления работ)" >
			<A id="CODE" labelwidth="500" />
			<A id="NAME"/>
			<A id="USED" name="Используется в документах" caption="Используется в документах" labelwidth="100" type="boolean"  local="true"  />
			<TI id="JOBSDIRECTIONS1983_UK" name="Направления работ с таким кодом уже существует" unique="CODE"/> 		
		</TABLE>
		<TABLE id="DOCS1983" name="Textual documents (текстовые документы)" >
			<A id="DOCNUM" labelwidth="200" width="60" name="Номер документа" caption="Номер" type="string" local="true" nulls="false" />
			<A id="DOCDATE" labelwidth="200" width="60" name="Дата документа" caption="Дата" type="date" local="true" nulls="false" formula="now()" />
			<A id="DAY_WEEK_VIRT" name="День недели" caption="День недели" labelwidth="100" width="40" type="list" readonly="true" virtual="true" formula="to_char(@DOCDATE, 'D')" >
				<AI id="0" name="Sunday" />
				<AI id="1" name="Monday" />
				<AI id="2" name="Tuesday" />
				<AI id="3" name="Wednesday" />
				<AI id="4" name="Thursday" />
				<AI id="5" name="Friday" />
				<AI id="6" name="Saturday" />
			</A>
			<A id="PERSON_ID" name="Исполнитель" caption="Исполнитель" />
			<GA caption="Работы">
				<A id="JOBSDIRECTIONS1983ID" name="Направления работ" caption="Направления работ" labelwidth="500" type="ref" table="JOBSDIRECTIONS1983" ret="CODE" form="JobsDirections1983" where="USED" local="true" />
				<A id="JOBSDIRECTIONS1983_VIRT" name="Наименование" caption="Наименование" labelwidth="500" type="string" nulls="true" virtual="true" formula="select NAME from JOBSDIRECTIONS1983 where id = @JOBSDIRECTIONS1983ID" local="true" />
			</GA>
			<A id="YEAR_U" name="Учетный год" caption="Учетный год" labelwidth="100" type="int" len="4" local="true" formula="to_char(now(), 'YYYY')" />
			<A id="NOTE" labelwidth="200" />
			<A id="OKVED_ID" name="Виды деятельности" caption="Виды деятельности" array="true" labelwidth="500" />
		</TABLE>
		<TABLE id="ABOUTUS1983" name="About us (info)" >
			<A id="ABOUTTXT"  name="Info about us" caption="Info About Us" type="text" local="true"  readonly="false" />
		</TABLE>
		<TABLE id="DOCSP1983" name="Спецификация документа">
			<A id="DOCSP1983ID" name="Спецификация документа" parentkey="cascade" type="ref" table="DOCS1983" ret="ID"></A>
			<A id="NAME"></A>
			<A id="NUM_DOCSP" name="Количество" caption="Количество" labelwidth="200" width="50" type="int" local="true"></A>
			<A id="NUN_DOCSP" name="Сумма" caption="Сумма" labelwidth="200" width="50" type="number" len="18.2" local="true"></A>
		</TABLE>
		<TABLE id="DOCFILE1983" name="Файлы">
			<A id="DOCS1983ID" name="Ссылка на документ" parentkey="cascade" type="ref" table="DOCS1983" ret="ID" />
			<A id="DESCRIPTION" name="Описание" caption="Описание" type="text" nulls="true" />
			<GA caption="Сведения о загруженном файле">
				<A id="FILELINKSID" name="Имя файла" caption="Имя" readonly="true"/>
				<A id="SIZEVIRT" name="Размер файла" caption="Размер" labelwidth="300" type="int" nulls="true" visible="form" readonly="true" virtual="true" formula="select f.size from filelinks f where f.id = @FILELINKSID"/>
				<A id="DOCDATEVIRT" name="Дата загрузки файла" caption="Дата загрузки" labelwidth="500" type="date" nulls="true" visible="form" readonly="true" virtual="true" formula="select f.docdate from filelinks f where f.id = @FILELINKSID"/>
			</GA>
		</TABLE>
	</TABLES>	
	<ACTIONS name="Действия">
		<ACTION id="MenfinSiteRef" name="Menfin Site" type="link" href="https://www.menfin.ru" visible="new" />
	</ACTIONS>
	<REPORTS name="Отчеты"/>
	<FORMS id="Forms" name="Формы">
		<FORM id="JobsDirections1983" name="Направления работ">
			<GRID id="JobsDirections1983" name="Направления работ" table="JOBSDIRECTIONS1983" actionlist="Archive"></GRID>
		</FORM>		
		<FORM id="Docs1983" name="Текстовый документы">
			<GRID id="Docs1983" name="Текстовый документы" table="DOCS1983"></GRID>
			<TABS name="FILES">
				<TAB name="Спецификация">
					<GRID id="Docsp1983" name="Спецификация Документа" table="DOCSP1983" />
				</TAB>
				<TAB name="Файлы">
					<GRID id="Docfile1983" name="фАЙЛЫ" table="DOCFILE1983" readonly="true">
						<MENU>
							<MI actionlist="addFilelinks;Update;View;Delete;MoveFolder;ConfigTables;loadFilelinks" />
						</MENU>
					</GRID>
				</TAB>
			</TABS>
		</FORM>
		<FORM id="Doc_1983" name="Текстовые документы">
			<TABS>
				<TAB name="Текстовые документы">
					<GRID id="Doc_1983" name="Текстовые документы" table="DOCS1983"></GRID>
				</TAB>
				<TAB name="Спецификации документа">
					<A id="DOCNUM_VIRT" caption="Номер" labelwidth="100" width="50" type="string" readonly="true" virtual="true" formula="select DOCNUM from DOCS1983 where id = @DOC1983ID" local="true"></A>
					<A id="DOCDATE_VIRT" caption="Дата" labelwidth="100" width="50" type="date" readonly="true" virtual="true" formula="select DOCDATE from DOCS1983 where id = @DOC1983ID" local="true"></A>
					<GRID id="Docsp_1983" name="Спецификация документа" table="DOCSP1983"></GRID>
				</TAB>
			</TABS>
		</FORM>

		<FORM id="AboutUS1983">
			<GRID id="AboutForm1983" name="About us" readonly="true" table="ABOUTUS1983"></GRID>
		</FORM>
	</FORMS>
</SYSTEM>
